import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import Sidebar from "@/components/sidebar/Sidebar";
import Head from "next/head";
import React, { useState } from "react";

type Props = {
  children: React.ReactNode;
  metaName?: string;
  metaContent?: string;
};

const BaseLayout: React.FC<Props> = ({ children }) => {
  const [isOpen, setIsOpen] = useState<boolean>(false);
  return (
    <>
      <Head>
        <title>Steykesyen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/S.svg" />
      </Head>
      <div className="relative overflow-hidden">
        <Sidebar isOpen={isOpen} />
        <Navbar isOpen={isOpen} setIsOpen={setIsOpen} />
        <main className="md:px-24 max-w-screen-xl mx-auto px-5">
          {children}
        </main>
        <Footer />
      </div>
    </>
  );
};

export default BaseLayout;
